config/routes.rb
Rails.application.routes.draw do

  #home
  root to:'pages#home'

  #about
  get 'about', to: 'pages#about'
  get 'about_road', to: 'pages#about_road'
  get 'about_brand', to: 'pages#about_brand'

  #adventure
  get 'adventure', to: 'pages#adventure'

  get 'adventures_road', to: 'pages#adventures_road'
  get 'adventures_offer', to: 'pages#adventures_offer'

  #shop
  get 'shop', to: 'pages#shop'

  get 'production', to: 'pages#production'
  get 'products', to: 'pages#products'

  get 'first_product', to: 'pages#first_product'
  get 'second_product', to: 'pages#second_product'
  get 'third_product', to: 'pages#third_product'
  get 'fourth_product', to: 'pages#fourth_product'

  #FAQ
  get 'faq', to: 'pages#faq'

  #contact
  get 'contact-me', to: 'messages#new', as: 'new_message'
  post 'contact-me', to: 'messages#create', as: 'create_message'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message
  include ActiveModel::Model
  attr_accessor :name, :email, :body
  validates :name, :email, :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def new
    @message = Message.new
  end

  def create
    message = Message.new(message_params)

    if message.valid?
      MessageMailer.contact_me(message).deliver_now
      redirect_to new_message_url, notice: 'Message received, thanks !'
    else
      render :new
    end
  end

  private
  def message_params
    params.require(:message).permit(:name, :email, :body)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def adventure
  end

  def adventures_road
  end

  def adventures_offer

  end

  def shop
  end

  def production
  end

  def products
  end

  def first_product
  end

  def second_product
  end

  def third_product
  end

  def fourth_product
  end

  def about_road
  end

  def about_brand
  end

  def faq
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MamaMotoWebsite</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width" />

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="//fonts.googleapis.com/css?family=Open+Sans:300,400,600,700&amp;lang=en" />
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" />
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav>
      <div class="nav-container">
        <div class="nav-left">
          <div class="logo">
            <a href='/'><%#= image_tag('logo.png', class:'mama_logo') %></a>
            <a href='/'><%= image_tag('http://res.cloudinary.com/dx8cyvfka/image/upload/v1511949323/socials/logo.png', class:'mama_logo') %></a>
          </div>
        </div>
        <div class="nav-right non-mobile-menu">
          <div class="nav-items">
            <%= link_to 'ABOUT', about_path, class:'nav-item'%>
            <%= link_to 'ADVENTURE', adventure_path, class:'nav-item'%>
            <%= link_to 'SHOP', shop_path, class:'nav-item'%>
            <%= link_to 'CONTACT', new_message_path, class:'nav-item' %>
            <%= link_to 'FAQ', faq_path, class:'nav-item' %>
          </div>

          <div class="dropdown mobile-menu">
            <button id="dLabel" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%=image_tag('http://res.cloudinary.com/dx8cyvfka/image/upload/v1511992853/menu-burger.png', class:'menu-burger') %>
            </button>
            <ul class="dropdown-menu" aria-labelledby="dLabel">
              <li><%= link_to 'ABOUT', about_path, class:'nav-item'%></li>
              <li><%= link_to 'ADVENTURE', adventure_path, class:'nav-item'%></li>
              <li><%= link_to 'SHOP', shop_path, class:'nav-item'%></li>
              <li><%= link_to 'CONTACT', new_message_path, class:'nav-item' %></li>
              <li><%= link_to 'FAQ', faq_path, class:'nav-item' %></li>
            </ul>
          </div>

          <div class="logo-moto">
            <%#= image_tag('logo_moto.png', class:'mama_logo_moto') %>
            <%= image_tag('http://res.cloudinary.com/dx8cyvfka/image/upload/v1511949324/socials/logo_moto.png', class:'mama_logo_moto') %>
          </div>
        </div>
      </div>
    </nav>
    <%= yield %>

    <footer>
      <div class="footer-container <%= current_page?('/') || current_page?('/about') || current_page?('/adventure') || current_page?('/shop') || current_page?('/contact-me') ? ' footer-container-home' : '' %>">
        <div class="top-line">
          <div class="socials">
            <a href="https://www.facebook.com/MamaMotoParisCapeTown/" target="_blank">
              <%#= image_tag('socials/facebook.png', class:'social-item') %>
              <%= image_tag('http://res.cloudinary.com/dx8cyvfka/image/upload/v1511947367/socials/facebook_tn7ool.png', class:'social-item') %>
            </a>
            <a href="https://www.instagram.com/mamamoto_pct/" target="_blank">
              <%#= image_tag('socials/instagram.png', class:'social-item') %>
              <%= image_tag('http://res.cloudinary.com/dx8cyvfka/image/upload/v1511947367/socials/instagram_hb6fpd.png', class:'social-item') %>
            </a>
            <a href="https://medium.com/@cindycherchevsky" target="_blank">
              <%#= image_tag('socials/medium.png', class:'social-item') %>
              <%= image_tag('http://res.cloudinary.com/dx8cyvfka/image/upload/v1511947367/socials/medium_bvt7hg.png', class:'social-item') %>
            </a>
            <a href="https://www.youtube.com/channel/UCSr3uK9z7yUdXUwOOcgfYrg" target="_blank">
              <%#= image_tag('socials/youtube.png', class:'social-item') %>
              <%= image_tag('http://res.cloudinary.com/dx8cyvfka/image/upload/v1511947367/socials/youtube_nkmsdu.png', class:'social-item') %>
            </a>
          </div>
        </div>
        <div class="bottom-line">
          <a href="https://www.linkedin.com/in/adrien-floor-23b9bb129/" target="_blank" class="credits">Made with &hearts; by Adrien Floor</a>
        </div>
      </div>
    </footer>

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </body>
</html>

app/views/messages/new.html.erb
<div class="contact-form-page">
  <div class="contact-banner">

    <div class="contact-form-container">
      <div class="form-headers">
        <h2 class="form-title">
          Tell me more about your next adventure ...
        </h2>
        <p class="form-paragraph">
          I'll get back to you as soon as possible !
        </p>
      </div>

        <%= form_for @message, url:new_message_url do |f| %>
        <%= notice %>
        <%= @message.errors.full_messages.join(', ') %>

        <div class="form-fields-box">
          <div class="form-fields">
            <%= f.text_field :name, placeholder: 'Your name' %>
            <%= f.email_field :email, placeholder: 'Your email' %>
            <%= f.text_area :body, placeholder: 'Your message' %>
          </div>
          <div class="form-submit-button">
            <%= f.submit 'Send' %>
          </div>
        </div>
      <% end %>
    </div>

  </div>
</div>

app/views/pages/about.html.erb
<div class="about-page">
  <div class="about-banner">
    <div class="about-sub-flexbox">
      <div class="road-box">
        <%= link_to 'ABOUT THE ROAD', about_road_path, class:'about-subtitle'%>
      </div>
      <div class="brand-box">
        <%= link_to 'ABOUT THE BRAND', about_brand_path, class:'about-subtitle'%>
      </div>
    </div>
  </div>
</div>

app/views/pages/about_brand.html.erb
<%= link_to about_path do %>
  <i class="material-icons arrow-back">arrow_back</i>
<% end %>

  <div class="about-brand-page">

    <div class="about-brand-title">" L'aventure, c'est l'aventure ... "</div>

    <div class="hr-box">
      <div class="hr-about-road-title"></div>
    </div>

    <div class="about-brand-intro">
      <p>Née de la passion pour l’aventure, c’est en traversant le monde à moto que l’univers de la
      marque Mama Moto s’est construit. C’est d’abord l’envie de racontrer des histoires de femmes d’actions :
      des aventurieres, des femmes qui osent, trangressent et brisent les clichés. Fières de plusieurs visages,
      elles portent sans complexes leurs forces et leurs faiblesses, dans une quête de liberté fondamentale et
      rèsolument moderne.</p>

      <p>Au centre de leur action ? L’envie de changer le monde, de bousculer, de réinventer, de révo-
      lutionner la façon dont nous consommons et dont nous produisons, en placant l’humain au
      coeur des priorités. Nous voulons montrer qu’il est possible d’entreprendre tout en respectant des
      valeurs sociales et ethiques.</p>
    </div>

    <div class="about-road-img-box">
      <%#= image_tag('about_page/about_brand/equipee_bra.jpg', class:'img-bra')%>
      <%= image_tag('http://res.cloudinary.com/dx8cyvfka/image/upload/v1511949648/about_page/about_brand/equipee_bra.jpg', class:'img-bra')%>
    </div>

    <hr>


    <h2>Nos valeurs: </h2>


    <h3>OSER</h3>
    <div class="about-brand-card">
      <div class="about-brand-card-description">
        <p>Une marque qui ose, tant par son discours décalé et audacieux
        que par ses choix, valorisant l’entreprenariat social et ethique.</p>

        <p>Une marque qui se joue des codes, une marque surprenante.
        Plus qu’un style vestimentaire nous representons un style de vie,
        vrai et authentique,qui se construit souvent en un instant ou
        tout peu basculer, ou l’on se lance...</p>
      </div>
      <div class="about-brand-card-img">
        <%#= image_tag('about_page/about_brand/oser2.jpg', class:'about-brand-img-card-right')%>
        <%= image_tag('http://res.cloudinary.com/dx8cyvfka/image/upload/v1511949652/about_page/about_brand/oser2.jpg', class:'about-brand-img-card-right')%>
      </div>
    </div>

    <h3>DECOUVRIR</h3>
    <div class="about-brand-card">
      <div class="about-brand-card-img">
        <%#= image_tag('about_page/about_brand/decouvrir2.jpg', class:'about-brand-img-card-left')%>
        <%= image_tag('http://res.cloudinary.com/dx8cyvfka/image/upload/v1511949646/about_page/about_brand/decouvrir2.jpg', class:'about-brand-img-card-left')%>
      </div>
      <div class="about-brand-card-description">
        <p>Pour Mama Moto la découverte est un enrichissement à double
        sens. Chacun apprend à travers des relations ou l’Humain à
        une place centrale.</p>

        <p>Nous sommes une marque humaine, bienveillante et émotionelle,
          qui découvre autant qu’elle fait découvrir.</p>

        <p>Construite sur un dialogue sincère, Mama Moto rassemble une
        génération d’aventuriers en quête de sens et d’authenticité.</p>
      </div>
    </div>

    <h3>AGIR</h3>
    <div class="about-brand-card">
      <div class="about-brand-card-description">
        <p>Conscient des défis de demain, nous produisons une marque
        éthique et responsable.</p>

        <p>Plus qu’une collection de vêtement, Mama Moto transmet ses
        valeurs et s’engage en développant ses collections de manière
        éco-responsables et solidaires.</p>

        <p>Nous travaillons avec des ateliers et des collectivités locales,
        et nos tissus sont issus de la filière éco friendly.</p>
      </div>
      <div class="about-brand-card-img">
        <%#= image_tag('about_page/about_brand/agir.jpg', class:'about-brand-img-card-right')%>
        <%= image_tag('http://res.cloudinary.com/dx8cyvfka/image/upload/v1511949645/about_page/about_brand/agir.jpg', class:'about-brand-img-card-right')%>
      </div>
    </div>

    <h3>TRANSMETTRE</h3>
    <div class="about-brand-card">
      <div class="about-brand-card-img">
        <%#= image_tag('about_page/about_brand/transmettre4.jpg', class:'about-brand-img-card-right')%>
        <%= image_tag('http://res.cloudinary.com/dx8cyvfka/image/upload/v1511949652/about_page/about_brand/transmettre4.jpg', class:'about-brand-img-card-right')%>
      </div>
      <div class="about-brand-card-description">
        <p>Mama Moto est une marque qui inspire. Nous souhaitons
        influencer les jeunes femmes à se constuire dans l’action et
        le dépassement des préjugés.</p>

        <p>A travers nos aventures nous souhaitons mettre en lumiere
        des femmes qui agissent avec bienvaillance sur les enjeux
        de demain.</p>

        <p>Une envie de construire et de rêver ensemble.</p>
      </div>
    </div>

    <a href="#" class="link-to-top">Haut de page</a>

</div>

app/views/pages/adventure.html.erb
<div class="adventure-page">
  <div class="adventure-banner">
    <div class="adventure-sub-flexbox">
      <%= link_to 'THE ROAD', adventures_road_path, class:'adventure-subtitle'%>
      <%= link_to 'YOUR TRIP', adventures_offer_path, class:'adventure-subtitle'%>
    </div>
  </div>
</div>

app/views/pages/adventures_offer.html.erb
<div class="adventures-pages">

  <%= link_to adventure_path do %>
    <i class="material-icons arrow-back">arrow_back</i>
  <% end %>

      <h3>L'offre Mama Moto</h3>

      <div class="mama-offer-box">

        <p>Je souhaite partager avec vous mes meilleurs road-books et mes plus belles adresses, loin des chemins touristiques, en Afrique du Sud, en Namibie ou au Lesotho.</p><br>

        <p class="bold">Voici les étapes de préparation de votre aventure :</p>

        <div class="card-mama-offer">
            <ul>
              <li> <i class="material-icons">portrait</i> Prise de contact: expliquez-moi quel motard (ou quelle motarde) vous êtes. Avez-vous déjà voyagé seul ? À moto? En off-road ? </li>
              <li> <i class="material-icons">access_time</i> Nous définissons une période de l'année en fonction de votre emploi du temps et des demandes ( les groupes sont constitués a partir de 5 riders ).</li>
              <li> <i class="material-icons">motorcycle</i> Nous choisissons une moto: BMW F700 GS, F800 GS, R1200 GS, R1200 Adventure... Vous pouvez aussi choisir de rouler sur des trails vintages des années 90, comme des Suzuki DR de 350 à 650 cm3 ou Yamaha Tenere XT 600.</li>
              <li> <i class="material-icons">done</i> Prise d'informations et validation du budget.</li>
            </ul>
        </div>

        <br>

        <p class="sub-info">Afin de respecter la liberté de chacun, chaque moto est équipée d'un GPS avec le road book du jour.
        Chacun est libre d'organiser sa journée comme il le souhaite et de rouler à son rythme...</p>

        <i class="material-icons icon-big">terrain</i>

    </div>

    <p class="bold conclusion-offer ">Mon désir est de partager ma vision du voyage et de l'aventure avec vous. N'hésitez pas à me <%= link_to 'contacter', new_message_path, class:'contact-link' %>, je serais ravie de vous accompagner pour une experience unique et pleine de surprises ! </p>


</div>

app/views/pages/adventures_road.html.erb
<div class="adventures-pages">

  <%= link_to adventure_path do %>
    <i class="material-icons arrow-back">arrow_back</i>
  <% end %>


  <h2 class="adventure-title">" Prendre la route, c'est ce qu'il doit arriver ... "</h2>

  <div class="hr-box">
    <div class="hr-adventure-title"></div>
  </div>


  <div class="adventure-text-box">
    <p class="first-adventure-paragraph">Je vous propose de me rejoindre pour une aventure à moto.</p>
  </div>

  <div class="img-top-adventure-box">
    <%#= image_tag('adventure_page/img-top.jpg', class:'img-top-adventure')%>
    <%= image_tag('http://res.cloudinary.com/dx8cyvfka/image/upload/v1511947463/adventure_page/img-top_nkcqbn.jpg', class:'img-top-adventure')%>
  </div>

  <div class="adventure-text-box">

    <p>Loin des voyages organisés par des professionnels du tourisme, je vous propose de vivre une experience singulière. Chaque aventure sera unique.
    Mon désir est de partager ma vision du voyage et de l'aventure avec vous.
    N'hésitez pas a me contacter, je serais ravie de vous accompagner sur les pistes d'Afrique du Sud. </p>

  </div>

  <div class="img-middle-adventure-box">
    <%#= image_tag('adventure_page/table-mountain.png', class:'img-middle-adventure')%>
    <%= image_tag('http://res.cloudinary.com/dx8cyvfka/image/upload/v1511947470/adventure_page/table-mountain_pubmql.png', class:'img-middle-adventure')%>
  </div>


<h3>Qu’est ce que l’aventure ?</h3><br>
    <div class="row">
      <div class="card">
        <p>A l’heure ou l’on peut rallier les bouts du monde en quelques heures d’avion, l’aventure est devenue un objet de consommation pour le tourisme de masse.
         Comment parler d’aventure, et comment la définir ?</p>
        <p>L’aventure pour Mama Moto est un style de vie qui implique un rapport à l’engagement, à l’isolement, et au risque.</p>
      </div>
      <div class="small-img-box">
        <%#= image_tag('adventure_page/small-img-1.jpg', class:'small-img')%>
        <%= image_tag('http://res.cloudinary.com/dx8cyvfka/image/upload/v1511947475/adventure_page/small-img-1_vlethd.jpg', class:'small-img')%>
      </div>
    </div>

    <div class="row">
      <div class="small-img-box">
        <%#= image_tag('adventure_page/small-img-2', class:'small-img')%>
        <%= image_tag('http://res.cloudinary.com/dx8cyvfka/image/upload/v1511947463/adventure_page/small-img-2_ubrah5.jpg', class:'small-img')%>
      </div>

      <div class="card">
        <p>La solitude et l’isolement sont des valeurs propres à l’aventure. La moto est un formidable moyen de les explorer.
          Seul dans son casque, on se laisse aller à ses pensées, on se connecte à ses désirs, ses rêves, son imagination.</p>
        <p>Chacun a sa façon de vivre la solitude, mais pour qu’elle soit bénéfique, elle ne peut être que choisie.
          Lorsque l'on est seul il n'y a pas d'autre choix que d'être maître de sa trajectoire, de s’engager, de prendre des décisions, un risque.</p>
      </div>
    </div>

    <div class="row">
      <div class="card">
        <p>L'aventure c’est aller vers des territoires que l’on ne connait pas, qu'ils soient physiques, socios ou intellectuels.
          C’est une façon de se mettre en déséquilibre, en difficulté. Il est primordial de sortir de ses certitudes et d'accepter d'aller vers une réalité que l’on ne maîtrise pas.</p>
        <p>Être un aventurier, c’est vouloir être bousculé.</p>
      </div>
      <div class="small-img-box">
        <%#= image_tag('adventure_page/small-img-3', class:'small-img')%>
        <%= image_tag('http://res.cloudinary.com/dx8cyvfka/image/upload/v1511947462/adventure_page/small-img-3_nwltln.jpg', class:'small-img')%>
      </div>
    </div>

      <p class="conclusion bold">Mama moto vous propose de vous accompagner dans ce voyage initiatique.</p>

      <div class="hr-box">
        <div class="hr-about-road-title"></div>
      </div>



</div>

app/views/pages/faq.html.erb
<div class="faq-page">

  <h1>FAQ</h1>

<h4>DELIVERY</h4>
<h5>WHAT ARE THE SHIPPING COSTS?</h5>

The shipping costs in Colissimo are €9 per order for metropolitan France for Preorders.

The shipping costs in Europe are €15 per order.

Shipping costs outside Europe are €20 per order.

<h5>WHAT ARE THE DELIVERY TIMES?</h5>

The delivery time in Colissimo is 3-4 days for France, 3-8 days for the other destinations.

<h5>HOW DO I TRACK MY PARCEL?</h5>

When sending your parcel a confirmation is sent to you by email containing the link to follow the status of your delivery.

<h5>WHAT IF I HAVE NOT RECEIVED MY PARCEL?</h5>

In case of absence from you during delivery, the carrier must normally leave a "notice of passage". On this notice, it is indicated when the carrier is to be ironed or where the parcel has been made available.

Sometimes the carrier does not leave a notice of passage. This is why we advise you to check regularly the status of your delivery via the parcel tracking number that has been forwarded to you.

If your parcel is advertised "delivered" but you have not received it, please check with your custodian or your neighbors if they did not receive it in your place.

If your parcel is announced "returned to Sender", please contact our customer service.



<h4>EXCHANGE</h4>
<h5>HOW DO I EXCHANGE AN ARTICLE?</h5>

If your order is not suitable for you, you can exchange within 15 days of receipt for a size above or below. Just follow the indications of the return sheet that is in your parcel.

If you have lost it or if you need anything else, contact customer service by email (john@asphalte-paris.com) or by phone at 09.54.41.38.25. We'll show you the way forward.

<h5>WHO TAKES CHARGE OF THE RETURN FEE?</h5>

Asphalt takes charge of the postal costs to exchange products for metropolitan France. On the other hand, at the International it is up to the customer to take charge of the return costs.



<h4>THE BRAND</h4>
<h5>WHO ARE WE?</h5>

Asphalt is a French brand, created in 2016 with the launch of its crowdfunding campaign The perfect sweater on ulule.



<h4>THE PRODUCTS</h4>
<h5>WHERE ARE THE PRODUCTS MADE?</h5>

All our products are made in partner companies that we choose carefully. For each product we receive prototypes from several factories and choose the best quality and then propose you to pre-order it on our site.

</div>

app/views/pages/fourth_product.html.erb
<div class="product-page">

  <h3> More details coming soon ;-)</h3>

</div>

app/views/pages/home.html.erb
<div class="container-home-page">
</div>

app/views/pages/products.html.erb
<div class="products-page">

  <div class="products-list">
    <div class="first-products-banner">
      <div data-turbolinks="false" class="products-card">
          <h2 class="products-title-banner">THE TANKWA BAG</h2>
          <%#= image_tag('shop_page/tankwa_bag.jpg', class:'image-products-card')%>
          <%= image_tag('http://res.cloudinary.com/dx8cyvfka/image/upload/v1511952201/shop_page/tankwa_bag_sw3qh6.jpg', class:'image-products-card')%>
          <%= link_to 'DISCOVER THE PRODUCT', first_product_path, class:'discover-title'%>
      </div>
    </div>
    <div class="second-products-banner">
      <div data-turbolinks="false" class="products-card">
          <h2 class="products-title-banner">THE KAROO BAG</h2>
          <%#= image_tag('shop_page/karoo_bag.jpg', class:'image-products-card')%>
          <%= image_tag('http://res.cloudinary.com/dx8cyvfka/image/upload/v1511952176/shop_page/karoo_bag_cc2jjx.jpg', class:'image-products-card')%>
          <%= link_to 'DISCOVER THE PRODUCT', second_product_path, class:'discover-title'%>
      </div>
    </div>
    <div class="third-products-banner">
      <div data-turbolinks="false" class="products-card">
          <h2 class="products-title-banner">ACCESSORIES</h2>
          <%#= image_tag('shop_page/candle.jpg', class:'image-products-card')%>
          <%= image_tag('http://res.cloudinary.com/dx8cyvfka/image/upload/v1511952164/shop_page/candle_cq33pq.jpg', class:'image-products-card')%>
          <%= link_to 'DISCOVER THE PRODUCTS', third_product_path, class:'discover-title'%>
      </div>
    </div>
    <div class="fourth-products-banner">
      <div data-turbolinks="false" class="products-card">
          <h2 class="products-title-banner">CLOTHING</h2>
          <%#= image_tag('shop_page/sweat_shirt.jpg', class:'image-products-card')%>
          <%= image_tag('http://res.cloudinary.com/dx8cyvfka/image/upload/v1511952193/shop_page/sweat_shirt_tzcljx.png', class:'image-products-card')%>
          <%= link_to 'DISCOVER THE PRODUCTS', fourth_product_path, class:'discover-title'%>
      </div>
    </div>

  </div>

</div>

app/views/pages/shop.html.erb
<div class="shop-page">
  <div class="shop-banner">
    <div class="shop-sub-flexbox">
      <%= link_to 'HOW WE WORK', production_path, class:'shop-subtitle'%>
      <%= link_to 'OUR PRODUCTS', products_path, class:'shop-subtitle'%>
    </div>
  </div>
</div>